### ISSUE TITLE
Great job :)

### ISSUE THREAD

**Issue by metabsd** [fitbeard/action-trigger-awx#9]
Hello, I find this github action very useful for us. I would like to know if it is possible to control the awxkit version to make your project indispensable for us. Otherwise I will have to create our own implementation to match our versions. Thank you very much for your excellent work.

**Comment by fitbeard** [comment]
Hi. To make this action fast its uses prebuilt docker layer with `awxkit`. Otherwise it will take a lot more times to start on runner - `awxkit` and dependencies must be compiled and installed on every execution of this action. Version mismatch is not big problem from my experience. This action based on `awx 19.4.0` successfully tested with all versions `15.x`+
